#!/bin/bash

# Create a new directory and enter it
function md() {
  mkdir -p "$@" && cd "$@" || exit
  #     └─ make parent directories if needed
}


# (f)ind by (n)ame
function fn() {
  ls ./**/*"$1"*
}


# atom package handling
function atom_pkg_install() {
  apm install --packages-file "$DOTFILESROOT"/src/atom/package-list.txt
}

function atom_pkg_update() {
  apm list --installed --bare > "$DOTFILESROOT"/src/atom/package-list.txt
}

function init_project-node {
  git init
  git config user.name "$(npm get init.author.name)"
  git config user.email "$(npm get init.author.email)"
  npx license "$(npm get init.license)"
  npx gitignore node
  npx covgen "$(npm get init.author.email)"
  npm init -y
  npx eslint --init
  echo -n "$(tput setaf 6)create initial commit (y/n)?$(tput sgr 0)"
  read -r REPLY
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    git add -A
    git commit -m "Initial commit"
  fi
}


# update node version manager
function update_nvm () {
  echo 'update Node Version Manager'
  cd "$HOME/.nvm" &&
  git fetch --quiet origin &&
  git checkout --quiet &&
  . "$HOME/.nvm/nvm.sh" &&
  echo 'nvm UPDATED'
}


# download mp3 with youtube-dl
function ydl() {
  # https://superuser.com/questions/555874/zsh-read-command-fails-within-bash-function-read1-p-no-coprocess
  echo -n "$(tput setaf 6)What is the YouTube link?$(tput sgr 0)"
    read -r REPLY

    if [[ $REPLY = *"www.youtube.com"* ]]; then

      source="$REPLY"

      PS3="Download video or audio? "
      select opt in Video Audio; do
        case $opt in
          Video)
            yt-dlp -S "ext" -o "$HOME/Downloads/Videos/%(title)s.%(ext)s" "$source"
          ;;
          Audio)
            yt-dlp -x --audio-quality 3 --audio-format mp3 -o "$HOME/Downloads/Music/%(title)s.%(ext)s" "$source"
          ;;
        esac
        ydl
      done
      y
    elif [[ $REPLY =~ ^[Xx]$ ]]; then
      return;
    else
      echo 'Link is not valid. Try again [or press x for exit]'
      ydl
    fi
}


# pdf helper functions
pdfreducesize()
{
   gs -q -dNOPAUSE -dBATCH -dSAFER -sDEVICE=pdfwrite -dCompatibilityLevel=1.3 -dPDFSETTINGS=/screen -dEmbedAllFonts=true -dSubsetFonts=true -dColorImageDownsampleType=/Bicubic -dColorImageResolution=144 -dGrayImageDownsampleType=/Bicubic -dGrayImageResolution=144 -dMonoImageDownsampleType=/Bicubic -dMonoImageResolution=144 -sOutputFile="$1".compressed.pdf "$1";
}

gllatest() {
    if [[ -z $1 ]]; then
        echo "No filename supplied"
        return
    elif [[ $1 == *.* ]]; then
        local pattern="**/$1"
    else
        local pattern="**/$1.*"
    fi
    git log -1 --pretty=format:"%H - %s (%an, %ar)" "${pattern}"
}
