#!/bin/bash

# Create a new directory and enter it
function md() {
  mkdir -p "$@" && cd "$@"
  #     └─ make parent directories if needed
}


# (f)ind by (n)ame
function fn() {
  ls **/*$1*
}


# atom package handling
function atom_pkg_install() {
  apm install --packages-file $DOTFILESROOT/src/atom/package-list.txt
}

function atom_pkg_update() {
  apm list --installed --bare > $DOTFILESROOT/src/atom/package-list.txt
}


# update node version manager
function update_nvm () {
  echo 'update Node Version Manager'
  cd $HOME/.nvm &&
  git fetch --quiet origin &&
  git checkout --quiet &&
  . $HOME/.nvm/nvm.sh &&
  echo 'nvm UPDATED'
}


# download mp3 with youtube-dl
function ydl() {
  # https://superuser.com/questions/555874/zsh-read-command-fails-within-bash-function-read1-p-no-coprocess
  echo -n "$(tput setaf 6)What is the YouTube link?$(tput sgr 0)"
    read REPLY

    if [[ $REPLY = *"www.youtube.com"* ]]; then
      youtube-dl -x --audio-quality 3 --audio-format mp3 -o "~/Downloads/Music/%(title)s.%(ext)s" $REPLY
      ydl
    elif [[ $REPLY =~ ^[Xx]$ ]]; then
      return;
    else
      echo 'Link is not valid. Try again [or press x for exit]'
      ydl
    fi
}
